export const FETCH_BOOKMARKS = 'FETCH_BOOKMARKS';
export const NEW_BOOKMARKS = 'NEW_BOOKMARKS';
export const SAVE_BOOKMARK = 'SAVE_BOOKMARK';
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';

export const GET_BOOKMARKS = 'GET_BOOKMARKS';
